#!/bin/bash
# scripts/run-all-gates.sh
# GENERATED BY AGENT 6 - DO NOT EDIT MANUALLY
set -euo pipefail

# Split-first guard - ensure gate-splitter.sh has been run
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EXPECTED_VERIFY_SCRIPTS=32

ACTUAL_VERIFY_SCRIPTS=$(ls -1 "$SCRIPT_DIR"/verify-*.sh 2>/dev/null | wc -l)
if [[ $ACTUAL_VERIFY_SCRIPTS -lt $EXPECTED_VERIFY_SCRIPTS ]]; then
  echo "[X] ERROR: Found $ACTUAL_VERIFY_SCRIPTS verify scripts, expected $EXPECTED_VERIFY_SCRIPTS"
  echo ""
  echo "    Scripts have not been extracted. Run this first:"
  echo "    bash docs/gate-splitter.sh"
  echo ""
  exit 1
fi

PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DOCS_DIR="$PROJECT_ROOT/docs"
BUILD_ID="build-$(date +%Y%m%d-%H%M%S)"
BUILD_START=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

echo "=== Build Gate Execution ==="
echo "Build ID: $BUILD_ID"
echo "Start: $BUILD_START"
echo ""

mkdir -p "$DOCS_DIR"

TOTAL_GATES=0
PASSED_GATES=0
FAILED_GATES=0

# JSON results array
echo "{" > "$DOCS_DIR/build-gate-results.json"
echo "  \"\$schema\": \"build-gate-results-v1\"," >> "$DOCS_DIR/build-gate-results.json"
echo "  \"buildId\": \"$BUILD_ID\"," >> "$DOCS_DIR/build-gate-results.json"
echo "  \"startTime\": \"$BUILD_START\"," >> "$DOCS_DIR/build-gate-results.json"

# Helper function to run gates and record results
run_gate() {
  local gate_name="$1"
  local gate_script="$2"
  shift 2
  local script_args=("$@")
  
  TOTAL_GATES=$((TOTAL_GATES + 1))
  
  if [[ ! -f "$gate_script" ]]; then
    echo "[X] FAIL: $gate_name (script not found)"
    FAILED_GATES=$((FAILED_GATES + 1))
    return 1
  fi
  
  local output
  local status
  if [[ ${#script_args[@]} -gt 0 ]]; then
    if output=$("$gate_script" "${script_args[@]}" 2>&1); then
      status="passed"
      PASSED_GATES=$((PASSED_GATES + 1))
      echo "[OK] $gate_name"
    else
      status="failed"
      FAILED_GATES=$((FAILED_GATES + 1))
      echo "[X] FAIL: $gate_name"
      echo "$output" | sed 's/^/    /'
    fi
  else
    if output=$("$gate_script" 2>&1); then
      status="passed"
      PASSED_GATES=$((PASSED_GATES + 1))
      echo "[OK] $gate_name"
    else
      status="failed"
      FAILED_GATES=$((FAILED_GATES + 1))
      echo "[X] FAIL: $gate_name"
      echo "$output" | sed 's/^/    /'
    fi
  fi
  
  # Append gate result to JSON (will finalize later)
  write_gate_result "$gate_name" "$status" "$output"
}

# Helper to write gate results (using function to scope local vars)
write_gate_result() {
  local gate="$1"
  local status="$2"
  local output="$3"
  local first=false
  
  if [[ $TOTAL_GATES -eq 1 ]]; then
    first=true
  fi
  
  if [[ "$first" == "false" ]]; then
    echo "," >> "$DOCS_DIR/build-gate-results.tmp"
  fi
  
  # Escape JSON special characters in output
  local escaped_output=$(echo "$output" | sed 's/\\/\\\\/g; s/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')
  
  echo "    {" >> "$DOCS_DIR/build-gate-results.tmp"
  echo "      \"gate\": \"$gate\"," >> "$DOCS_DIR/build-gate-results.tmp"
  echo "      \"status\": \"$status\"," >> "$DOCS_DIR/build-gate-results.tmp"
  echo "      \"output\": \"$escaped_output\"" >> "$DOCS_DIR/build-gate-results.tmp"
  echo "    }" >> "$DOCS_DIR/build-gate-results.tmp"
}

# Initialize results temp file
echo "  \"gates\": [" > "$DOCS_DIR/build-gate-results.tmp"

# Phase 0: Preflight checks
echo ""
echo "=== Phase 0: Preflight Checks ==="
run_gate "preflight-artifacts" "$SCRIPT_DIR/verify-preflight-artifacts.sh"
run_gate "no-forbidden-artifacts" "$SCRIPT_DIR/verify-no-forbidden-artifacts.sh"
run_gate "spec-size-budget" "$SCRIPT_DIR/verify-spec-size-budget.sh"
run_gate "no-placeholders" "$SCRIPT_DIR/verify-no-placeholders.sh"
run_gate "env-var-usage-proof" "$SCRIPT_DIR/verify-env-var-usage-proof.sh"
run_gate "multi-tenant-isolation" "$SCRIPT_DIR/verify-multi-tenant-isolation.sh"

# Phase 1: Product Definition gates
echo ""
echo "=== Phase 1: Product Definition ==="
run_gate "scope-invariants" "$SCRIPT_DIR/verify-scope-invariants.sh"
run_gate "complete-deferrals" "$SCRIPT_DIR/verify-complete-deferrals.sh"

# Phase 2: System Architecture gates
echo ""
echo "=== Phase 2: System Architecture ==="
run_gate "env-manifest-schema" "$SCRIPT_DIR/verify-env-manifest-schema.sh"
run_gate "config-files-required" "$SCRIPT_DIR/verify-config-files-required.sh"
run_gate "health-db-connectivity" "$SCRIPT_DIR/verify-health-db-connectivity.sh"
run_gate "no-wildcard-cors" "$SCRIPT_DIR/verify-no-wildcard-cors.sh"
run_gate "encryption-binary" "$SCRIPT_DIR/verify-encryption-binary.sh"

# Phase 3: Data Modeling gates
echo ""
echo "=== Phase 3: Data Modeling ==="
run_gate "cascade-completeness" "$SCRIPT_DIR/verify-cascade-completeness.sh"
run_gate "project-scope-strategy" "$SCRIPT_DIR/verify-project-scope-strategy.sh"
run_gate "index-strategy" "$SCRIPT_DIR/verify-index-strategy.sh"
run_gate "schema-imports" "$SCRIPT_DIR/verify-schema-imports.sh"

# Phase 4: API Contract gates (structural)
echo ""
echo "=== Phase 4: API Contract ==="
run_gate "body-validation" "$SCRIPT_DIR/verify-body-validation.sh"
run_gate "upload-config-sourced" "$SCRIPT_DIR/verify-upload-config-sourced.sh"
run_gate "organisation-endpoint-naming" "$SCRIPT_DIR/verify-organisation-endpoint-naming.sh"
run_gate "mvp-scope-boundaries" "$SCRIPT_DIR/verify-mvp-scope-boundaries.sh"
run_gate "token-scoped-routing" "$SCRIPT_DIR/verify-token-scoped-routing.sh"
run_gate "error-handlers" "$SCRIPT_DIR/verify-error-handlers.sh"

# Phase 4: Per-endpoint expansion gates
SERVICE_CONTRACTS="$DOCS_DIR/service-contracts.json"
if [[ -f "$SERVICE_CONTRACTS" ]]; then
  ENDPOINT_COUNT=$(grep -c '"path"' "$SERVICE_CONTRACTS" || echo "0")
  if [[ $ENDPOINT_COUNT -gt 0 ]]; then
    echo ""
    echo "=== Phase 4: Per-Endpoint Gates ($ENDPOINT_COUNT endpoints) ==="
    
    for i in $(seq 0 $((ENDPOINT_COUNT - 1))); do
      ENDPOINT_PATH=$(grep -o '"path": "[^"]*"' "$SERVICE_CONTRACTS" | sed -n "$((i+1))p" | cut -d'"' -f4)
      
      # Sanitize endpoint path for gate ID (remove leading/trailing /, replace / with -, strip special chars)
      GATE_ID=$(echo "$ENDPOINT_PATH" | sed 's|^/||; s|/$||; s|/|-|g; s|[^a-zA-Z0-9_-]||g')
      
      run_gate "endpoint-status-$GATE_ID" "$SCRIPT_DIR/verify-endpoint-status.sh" "$i"
      run_gate "route-service-alignment-$GATE_ID" "$SCRIPT_DIR/verify-route-service-alignment.sh" "$i"
      run_gate "pagination-max-$GATE_ID" "$SCRIPT_DIR/verify-pagination-max.sh" "$i"
      run_gate "status-enums-$GATE_ID" "$SCRIPT_DIR/verify-status-enums.sh" "$i"
    done
    
    # Upload-specific E2E gate (runs once for upload endpoints)
    run_gate "upload-e2e" "$SCRIPT_DIR/verify-upload-e2e.sh"
  fi
fi

# Phase 5: UI Specification gates
echo ""
echo "=== Phase 5: UI Specification ==="
run_gate "ui-canonical-paths" "$SCRIPT_DIR/verify-ui-canonical-paths.sh"
run_gate "ui-api-alignment" "$SCRIPT_DIR/verify-ui-api-alignment.sh"
run_gate "ui-self-consistency" "$SCRIPT_DIR/verify-ui-self-consistency.sh"
run_gate "no-deferred-pages" "$SCRIPT_DIR/verify-no-deferred-pages.sh"

# Finalize JSON
BUILD_END=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

cat "$DOCS_DIR/build-gate-results.tmp" >> "$DOCS_DIR/build-gate-results.json"
rm "$DOCS_DIR/build-gate-results.tmp"

echo "  ]," >> "$DOCS_DIR/build-gate-results.json"
echo "  \"endTime\": \"$BUILD_END\"," >> "$DOCS_DIR/build-gate-results.json"
echo "  \"summary\": {" >> "$DOCS_DIR/build-gate-results.json"
echo "    \"total\": $TOTAL_GATES," >> "$DOCS_DIR/build-gate-results.json"
echo "    \"passed\": $PASSED_GATES," >> "$DOCS_DIR/build-gate-results.json"
echo "    \"failed\": $FAILED_GATES" >> "$DOCS_DIR/build-gate-results.json"
echo "  }" >> "$DOCS_DIR/build-gate-results.json"
echo "}" >> "$DOCS_DIR/build-gate-results.json"

# Update build transcript
cat > "$DOCS_DIR/build-transcript.md" << EOF
# Build Transcript

## Execution Results

| Metric | Value |
|--------|-------|
| Build ID | $BUILD_ID |
| Start Time | $BUILD_START |
| End Time | $BUILD_END |
| Total Gates | $TOTAL_GATES |
| Passed | $PASSED_GATES |
| Failed | $FAILED_GATES |

> See \`docs/build-gate-results.json\` for detailed results.

**Status:** $(if [[ $FAILED_GATES -eq 0 ]]; then echo "PASSED"; else echo "FAILED ($FAILED_GATES failures)"; fi)
EOF

echo ""
echo "=== Build Summary ==="
echo "Total Gates: $TOTAL_GATES"
echo "Passed: $PASSED_GATES"
echo "Failed: $FAILED_GATES"
echo ""

if [[ $FAILED_GATES -gt 0 ]]; then
  echo "[X] BUILD FAILED"
  echo "See docs/build-gate-results.json for details"
  exit 1
else
  echo "[OK] BUILD PASSED"
  echo "Results: docs/build-gate-results.json"
  exit 0
fi
