#!/bin/bash
set -e

# ============================================================================
# QA Scripts Splitter
# ============================================================================
# Purpose: Extract individual QA scripts from qa-scripts-reference.md
# Generated by Agent 7 v96
# Safety: File extraction only - no network or destructive operations

echo "=== QA Scripts Splitter ==="
echo "Extracting QA scripts from docs/qa-scripts-reference.md"

# Verify source file exists
if [[ ! -f "docs/qa-scripts-reference.md" ]]; then
  echo "[ERROR] docs/qa-scripts-reference.md not found"
  echo "Run Agent 7 first to generate QA scripts reference"
  exit 1
fi

# Create scripts directory
mkdir -p scripts

# Safety check: prevent overwrites without confirmation
EXISTING_SCRIPTS=($(find scripts -name "qa-*.sh" -o -name "run-all-qa-tests.sh" 2>/dev/null || true))
if [[ ${#EXISTING_SCRIPTS[@]} -gt 0 ]]; then
  echo "[ERROR] QA scripts already exist in scripts/ directory"
  echo "Existing files:"
  printf '%s\n' "${EXISTING_SCRIPTS[@]}"
  echo ""
  echo "Remove existing files first or use different output directory"
  exit 1
fi

# Extract scripts using file markers
CURRENT_FILE=""
INSIDE_SCRIPT=false
SCRIPT_COUNT=0

while IFS= read -r line; do
  # Check for file marker
  if [[ "$line" =~ ^#=====\ FILE:\ (.*)\ =====#$ ]]; then
    # Close previous file if open
    if [[ -n "$CURRENT_FILE" ]]; then
      echo "[OK] Extracted $CURRENT_FILE"
      SCRIPT_COUNT=$((SCRIPT_COUNT + 1))
    fi
    
    # Start new file
    CURRENT_FILE="${BASH_REMATCH[1]}"
    INSIDE_SCRIPT=true
    
    # Create file with proper permissions
    touch "$CURRENT_FILE"
    chmod +x "$CURRENT_FILE"
    continue
  fi
  
  # Write content to current file if inside script
  if [[ "$INSIDE_SCRIPT" == "true" && -n "$CURRENT_FILE" ]]; then
    echo "$line" >> "$CURRENT_FILE"
  fi
  
done < docs/qa-scripts-reference.md

# Close final file
if [[ -n "$CURRENT_FILE" ]]; then
  echo "[OK] Extracted $CURRENT_FILE"
  SCRIPT_COUNT=$((SCRIPT_COUNT + 1))
fi

echo ""
echo "=== Extraction Complete ==="
echo "Scripts extracted: $SCRIPT_COUNT"
echo ""

# Verify expected scripts exist
EXPECTED_SCRIPTS=(
  "scripts/qa-acquire-tokens.sh"
  "scripts/qa-health-check.sh"
  "scripts/qa-crud-smoke.sh"
  "scripts/qa-rbac-enforcement.sh"
  "scripts/qa-file-upload-mime.sh"
  "scripts/qa-tenancy-isolation.sh"
  "scripts/qa-unauthenticated-access.sh"
  "scripts/qa-input-validation.sh"
  "scripts/qa-response-format.sh"
  "scripts/qa-cors-preflight.sh"
  "scripts/run-all-qa-tests.sh"
)

MISSING_COUNT=0
for script in "${EXPECTED_SCRIPTS[@]}"; do
  if [[ ! -f "$script" ]]; then
    echo "[ERROR] Missing expected script: $script"
    MISSING_COUNT=$((MISSING_COUNT + 1))
  fi
done

if [[ $MISSING_COUNT -gt 0 ]]; then
  echo "[ERROR] $MISSING_COUNT expected scripts are missing"
  exit 1
fi

echo "All expected scripts extracted successfully"
echo ""
echo "Next steps:"
echo "1. Set BASE_URL environment variable"
echo "2. For mutation tests: export QA_ALLOW_MUTATION=true"
echo "3. Start application server"
echo "4. Run: bash scripts/run-all-qa-tests.sh"
